# Generated by Django 5.2.6 on 2025-11-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flower',
            options={'ordering': ['title'], 'verbose_name': 'Цветок', 'verbose_name_plural': 'Цветы'},
        ),
        migrations.AddField(
            model_name='flower',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='flowers/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='flower',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
