# Generated by Django 5.2.6 on 2025-12-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0002_alter_flower_options_flower_image_flower_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='flower',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='flower',
            name='available',
        ),
        migrations.RemoveField(
            model_name='flower',
            name='created',
        ),
        migrations.RemoveField(
            model_name='flower',
            name='updated',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='flower',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Остаток'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
